Listing 9-3: Generate an insecure RSA private key using the OpenSSL toolkit.

In [2]:
openssl version

OpenSSL 1.1.1q  5 Jul 2022


In [3]:
openssl genrsa --help

Usage: genrsa [options]
Valid options are:
 -help               Display this summary
 -3                  Use 3 for the E value
 -F4                 Use F4 (0x10001) for the E value
 -f4                 Use F4 (0x10001) for the E value
 -out outfile        Output the key to specified file
 -rand val           Load the file(s) into the random number generator
 -writerand outfile  Write random data to the specified file
 -passout val        Output file pass phrase source
 -*                  Encrypt the output with any supported cipher
 -engine val         Use engine, possibly a hardware device
 -primes +int        Specify number of primes


Note, OpenSSL now warns for RSA keys as short as 31 bits.

In [4]:
openssl genrsa 31

Generating RSA private key, 31 bit long modulus (2 primes)
140527123481600:error:04081078:rsa routines:rsa_builtin_keygen:key size too small:crypto/rsa/rsa_gen.c:78:


: 1

In [9]:
openssl genrsa 384

Generating RSA private key, 384 bit long modulus (2 primes)
139956109689856:error:04081078:rsa routines:rsa_builtin_keygen:key size too small:crypto/rsa/rsa_gen.c:78:


: 1

In [10]:
openssl genrsa 512

Generating RSA private key, 512 bit long modulus (2 primes)
.....+++++++++++++++++++++++++++
.+++++++++++++++++++++++++++
e is 65537 (0x010001)
-----BEGIN RSA PRIVATE KEY-----
MIIBOgIBAAJBALmohRysxHPsBa03jxWXzkL525wwmS8goEP86ID3bpzNLeMP0buA
0BJ/6sgmV04xLZaeOTCzmraeSlmTh8hnQ3cCAwEAAQJAUIzPA/vpWCok5FxglgvB
D8n8AC4NqCbNofHOpnWz5g9Z/uSo/AUiB3c4SssP2VhzZq7bXC0ehy0tgNSXQhKB
kQIhAODnp0MMVljIxia3VJ8+22tVeVfmhILo0oanErBzUrFVAiEA01PCzr7idQOG
Th9NZo7tWYkrDlCk3i4ZFCaXUAZSUZsCIQC+UCiAmxMCJDtRDbek3YrNA9IfqKgf
IqbrXLt65stl1QIgM/XaZl9E6ySMt1S3AUqPTX6OmZx2jTKkc/HxLnn/b5UCIGYT
rwLtLP1hHUAUmltX5PQT1KVirF+piVcxApGT1VnK
-----END RSA PRIVATE KEY-----


Looks like the updated warning threshold for this version of OpenSSL is somewhere between 384 and 512 bits.